### ISSUE TITLE
task TrafficJunction-v1 cannot work

### ISSUE THREAD

**Issue by GeorgeDUT** [koulanurag/ma-gym#13]
I use: env= gym.make("TrafficJunction-v1")
want to get a traffic control task.
But it cannot work, it returns that:

Traceback (most recent call last):
  File "xxx/traffic_test.py", line 74, in <module>
    testcmarl()
  File "xxx/traffic_test.py", line 37, in testcmarl
    obs = env.reset()
  File "xxx/ma-gym/ma_gym/envs/traffic_junction/traffic_junction.py", line 141, in reset
    return self.get_agent_obs()
  File "xxx/ma-gym/ma_gym/envs/traffic_junction/traffic_junction.py", line 85, in get_agent_obs
    pos = self.agent_pos[agent_i]
KeyError: 0

**Comment by koulanurag** [comment]
Hi @GeorgeDUT 

Please , refer here : #12

**Comment by GeorgeDUT** [comment]
> Hi @GeorgeDUT
> 
> Please , refer here : #12

Thanks,
So much the better if you can continue to develop TrafficJunction-v1～ it's a nice scenario.

**Comment by koulanurag** [comment]
Thanks to @rafaelmp2 , This env. has been added to `master` branch
